### PR TITLE
Use the Slack App Icon to represent Slack

### PR DESCRIPTION
**Pull request by paulcbetts**
## TODO:

- [x] Make sure Preview.app exported this properly
- [x] pngcrush the image

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Mind making it 144 x 144 like previously?

**Comment by paulcbetts** [comment]
@kevinsawicki On the page, it's being scaled to 96x96, both have a reasonable ratio (144/96 => 1.5, 128/96 => 4/3rds)

**Comment by kevinsawicki** [comment]
> On the page, it's being scaled to 96x96, both have a reasonable ratio (144/96 => 1.5, 128/96 => 4/3rds)

Hmm, it should be 72x72 on screen
screen shot 2015-10-07 at 9 59 21 am

We may want resize the icons in the future so having 144x144 consistently across all of them provides more flexibility there.

**Comment by kevinsawicki** [comment]
Closing this out for now, can reopen once it is updated :star2:

**Pull request closed without merging**
