### PR TITLE
Add AIRTAME icon

### PR DESCRIPTION
**Pull request by pierrefourgeaud**
After discussing with zcbenz, here comes the pull request.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Do you work on AIRTAME? We like to get approval from someone at the company before using their logo on the page.  Thanks.

**Comment by pierrefourgeaud** [comment]
Yes I do. I will try to get the CTO to confirm here.

**Comment by atiti** [comment]
Hi guys,

Attila, CTO from AIRTAME here. First of all, thank you all for Electron, it's super awesome!
Pierre has been leading the development of our new PC/Mac application using Electron. :-)

**Comment by kevinsawicki** [comment]
@atiti  @pierrefourgeaud the icon doesn't appear to be centered, can you upload the raw 512x512 png app icon used on Mac and then I can resize it to match the other ones on the page?  Thanks.

**Comment by pierrefourgeaud** [comment]
@kevinsawicki I just amended the commit with the new icon: 512x512 and centered.

**Comment by kevinsawicki** [comment]
> I just amended the commit with the new icon: 512x512 and centered.

@pierrefourgeaud awesome, thanks so much for this :+1:

**Pull request merged**
