### PR TITLE
Add Friends and Geojsonapp

### PR DESCRIPTION
**Pull request by kevinsawicki**
Adds two more awesome apps to the open source section.

/cc @maxogden should it be `Friends` or `FRIENDS`?

/cc @mick

### CODE REVIEW

**Comment by maxogden** [comment]
Friends :)

On Thursday, April 30, 2015, Kevin Sawicki <notifications@github.com> wrote:

> /cc @jlord <https://github.com/jlord>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/electron.atom.io/pull/18#issuecomment-97855256>.
>


-- 
Sent from my phone

**Comment by kevinsawicki** [comment]
:ship:

**Comment by jlord** [comment]
:clap: haha

**Comment by mick** [comment]
:tada: thanks for adding geojsonapp!

**Pull request merged**
